spring:
  application:
    name: X-Ray Document Managment System
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/document_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      format_sql: false
      open-in-view: false

rsa:
  private-key: "classpath:certs/private.pem"
  public-key: "classpath:certs/public.pem"
